id: A091A7777
title: Prayer to the Siddha Virūpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:27:48.177880
  last_modified_at: 2022-03-01 02:27:48.177888
